name: Add PWA Support (Fixed)

on:
  workflow_dispatch:

jobs:
  add-pwa:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Create manifest.json
      run: |
        cat > manifest.json << 'EOF'
        {
          "name": "Управление бригадами и складом",
          "short_name": "Бригады",
          "description": "Система управления бригадами и складом",
          "start_url": "/",
          "display": "standalone",
          "background_color": "#667eea",
          "theme_color": "#667eea",
          "orientation": "portrait-primary",
          "icons": [
            {
              "src": "https://via.placeholder.com/192x192/667eea/ffffff.png?text=📱",
              "sizes": "192x192",
              "type": "image/png",
              "purpose": "any maskable"
            },
            {
              "src": "https://via.placeholder.com/512x512/667eea/ffffff.png?text=📱",
              "sizes": "512x512",
              "type": "image/png",
              "purpose": "any maskable"
            }
          ]
        }
        EOF
        
    - name: Create service worker
      run: |
        cat > sw.js << 'EOF'
        const CACHE_NAME = 'brigades-app-v1.0.0';
        const STATIC_CACHE_URLS = ['/', '/index.html', '/manifest.json'];
        
        self.addEventListener('install', event => {
          console.log('Service Worker installing...');
          event.waitUntil(
            caches.open(CACHE_NAME)
              .then(cache => {
                console.log('Opened cache');
                return cache.addAll(STATIC_CACHE_URLS);
              })
              .then(() => self.skipWaiting())
          );
        });
        
        self.addEventListener('activate', event => {
          console.log('Service Worker activating...');
          event.waitUntil(
            caches.keys().then(cacheNames => {
              return Promise.all(
                cacheNames.map(cacheName => {
                  if (cacheName !== CACHE_NAME) {
                    return caches.delete(cacheName);
                  }
                })
              );
            }).then(() => self.clients.claim())
          );
        });
        
        self.addEventListener('fetch', event => {
          if (event.request.method !== 'GET') return;
          
          event.respondWith(
            caches.match(event.request)
              .then(cachedResponse => {
                if (cachedResponse) {
                  return cachedResponse;
                }
                
                return fetch(event.request)
                  .then(response => {
                    if (!response || response.status !== 200 || response.type !== 'basic') {
                      return response;
                    }
                    
                    const responseToCache = response.clone();
                    caches.open(CACHE_NAME)
                      .then(cache => {
                        cache.put(event.request, responseToCache);
                      });
                    
                    return response;
                  })
                  .catch(() => {
                    return caches.match('/');
                  });
              })
          );
        });
        EOF
        
    - name: Modify HTML for PWA
      run: |
        # Проверяем есть ли уже PWA теги
        if ! grep -q "manifest.json" index.html; then
          # Добавляем PWA мета-теги в head
          sed -i '/<title>/a \
        <!-- PWA Meta tags -->\
        <meta name="apple-mobile-web-app-capable" content="yes">\
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">\
        <meta name="apple-mobile-web-app-title" content="Бригады">\
        <meta name="mobile-web-app-capable" content="yes">\
        <meta name="msapplication-TileColor" content="#667eea">\
        <link rel="manifest" href="manifest.json">' index.html
        fi
        
        # Добавляем PWA JavaScript если его еще нет
        if ! grep -q "initializePWA" index.html; then
          sed -i '/<\/body>/i \
        <script>\
        // PWA инициализация\
        function initializePWA() {\
            console.log("Initializing PWA...");\
            \
            if ("serviceWorker" in navigator) {\
                navigator.serviceWorker.register("/sw.js")\
                    .then(registration => {\
                        console.log("SW registered:", registration);\
                    })\
                    .catch(error => {\
                        console.log("SW registration failed:", error);\
                    });\
            }\
            \
            let deferredPrompt;\
            \
            window.addEventListener("beforeinstallprompt", (e) => {\
                console.log("beforeinstallprompt fired");\
                e.preventDefault();\
                deferredPrompt = e;\
                \
                const installBtn = document.createElement("button");\
                installBtn.textContent = "📱 Установить приложение";\
                installBtn.id = "pwa-install-btn";\
                installBtn.style.cssText = "position: fixed; bottom: 90px; right: 20px; z-index: 1000; background: #28a745; color: white; border: none; padding: 12px 16px; border-radius: 8px; cursor: pointer; font-size: 14px; box-shadow: 0 4px 12px rgba(40, 167, 69, 0.3);";\
                \
                installBtn.onclick = async () => {\
                    if (deferredPrompt) {\
                        deferredPrompt.prompt();\
                        const { outcome } = await deferredPrompt.userChoice;\
                        console.log("Install outcome:", outcome);\
                        deferredPrompt = null;\
                        installBtn.remove();\
                    }\
                };\
                \
                document.body.appendChild(installBtn);\
            });\
            \
            window.addEventListener("appinstalled", () => {\
                console.log("PWA installed successfully!");\
                const installBtn = document.getElementById("pwa-install-btn");\
                if (installBtn) installBtn.remove();\
            });\
        }\
        \
        // Запускаем PWA инициализацию\
        if (document.readyState === "loading") {\
            document.addEventListener("DOMContentLoaded", initializePWA);\
        } else {\
            initializePWA();\
        }\
        </script>' index.html
        fi
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action PWA"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🚀 Add PWA support: manifest, service worker, install functionality"
          git push
        fi
